---
engines:
  bundler-audit:
    enabled: true
  brakeman:
    enabled: true
    checks:
      mass_assign_call:
        enabled: false # We use Strong Parameters instead
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
        #mass_threshold: 30
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  reek:
    enabled: true
    checks:
      TooManyStatements:
        enabled: true
        max_statements: 12
      DuplicateMethodCall:
        enabled: true
        max_calls: 2
      IrresponsibleModule:
        enabled: false
    exclude_paths:
      - db/migrate/*
  scss-lint:
     enabled: true
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
