AllCops:
  Exclude:
    - "**/db/**/*"

Metrics/LineLength:
  Max: 254

Lint/UnusedBlockArgument:
  Enabled: false

Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false
